/**
 * Type declarations for virtual:pwa-register module generated by vite-plugin-pwa
 */

declare module "virtual:pwa-register" {
	import type { RegisterSWOptions } from "vite-plugin-pwa/types";

	export function registerSW(
		options?: RegisterSWOptions,
	): ((reloadPage?: boolean) => Promise<void>) | undefined;
}
